window.NAIS2_CF_GUIDE_STEPS = [
  {
    title: '找到 Workers 页面入口',
    description: '优先点击页面中和 Workers、Workers & Pages、Compute 相关的入口。',
    fallback: '如果没找到，先看看左侧导航、顶部导航，或者搜索 “Workers / Workers & Pages / Compute”。',
    selectors: [
      'a[href*="workers-and-pages"]',
      'a[href*="workers"]',
      'button[data-testid*="workers"]',
      'nav a',
      'aside a',
      'button',
      'a',
    ],
    textHints: ['Workers', 'Workers & Pages', 'Compute', '计算', '工作线程'],
  },
  {
    title: '创建新的 Worker',
    description: '找到 Create、Create application、Start with Hello World 或 New Worker 相关按钮。',
    fallback: '如果没找到，通常需要先进入 Workers & Pages 页面，再看右上角或主内容区域的 Create / Create application。',
    selectors: [
      'button[data-testid*="create"]',
      'a[href*="create"]',
      'button',
      'a',
    ],
    textHints: ['Create', 'Create application', 'Start with Hello World', 'New Worker', 'Deploy a Worker', 'Create Worker', '创建'],
  },
  {
    title: '先部署默认 Hello World',
    description: '这个页面里的 Worker preview 只是预览区，不可直接编辑。先点击 Deploy 创建 Worker。',
    fallback: '如果没找到，先确认你还在 Deploy Hello World 这一步，按钮通常在右下角。',
    selectors: [
      'button[data-testid*="deploy"]',
      'button',
      'a',
    ],
    textHints: ['Deploy', 'Deploy Worker', 'Hello World', 'Create Worker'],
  },
  {
    title: '进入真正的代码编辑器',
    description: '部署默认 Worker 后，进入真正可编辑代码的页面，再准备自动填入模板。',
    fallback: '如果没找到，先看看页面里的 Edit code、Quick edit、Code、Worker overview 等入口。',
    selectors: [
      'button[data-testid*="edit"]',
      'a[href*="/edit"]',
      'button[data-testid*="code"]',
      'button',
      'a',
    ],
    textHints: ['Edit code', 'Quick edit', 'Code', 'Edit Worker', 'Worker overview', '编辑'],
  },
  {
    title: '定位真正的代码编辑器',
    description: '现在应该已经进入可编辑代码的页面，准备让插件自动填入 Worker 模板。如果自动填入失败，请先点击中间代码区，按一次 Ctrl+A，再点“我已按 Ctrl+A，继续写入”。',
    fallback: '如果没找到，先确认你已经进入 Worker 编辑器页面；通常会看到 Monaco 编辑器、代码区或 textarea。',
    selectors: [
      '.monaco-editor',
      '.cm-editor',
      '[data-testid*="editor"]',
      '[role="code"]',
      'textarea.inputarea',
      'textarea',
      '[class*="editor"]',
      '[class*="monaco"]',
    ],
    textHints: ['export default', 'console.info', 'Response', 'worker', 'fetch', 'Hello World'],
  },
  {
    title: '准备部署 Worker',
    description: '代码填入后，再点击 Deploy / Save and Deploy。',
    fallback: '如果没找到，部署按钮一般在右上角、底部，或编辑器上方的操作区。',
    selectors: [
      'button[data-testid*="deploy"]',
      'button[data-testid*="save"]',
      'button',
      'a',
    ],
    textHints: ['Deploy', 'Save and deploy', 'Save', 'Deploy application', 'Continue to project', '继续', '保存'],
  },
]
